[pytest]    #Alles was hier drunter steht sind Konfigurationseinstellungen für pytest
# Ohne diesen Header würde pytest die Datei ignorieren.
asyncio_mode = auto

#Ohne diese Zeile müsste man jeden async Test manuell mit @pytest.mark.asyncio
#markieren und jede async Fixture mit @pytest_asyncio.fixture()
asyncio_default_fixture_loop_scope = function
# jede Testfunktion bekommt ihren eigenen frischen Event Loop.

addopts = -v -s --tb=short
# additional options: -v für verbose output (zeigt jeden einzelnen Test mit seinem Namen und PASSED/FAILED an), -s damit print statements in den tests angezeigt werden, --tb=short für kürzere Tracebacks bei Fehlern
# wird nur der relevante Teil des Fehlers angezeigt, nicht der komplette lange Stacktrace.
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
#Beide werden mit ignore unterdrückt weil sie in Tests störend sind — s
#sie kommen oft aus Bibliotheken die man selbst nicht kontrolliert und haben nichts mit dem eigentlichen Testergebnis zu tun.



#eventloop ----> #######


#Der Event Loop ist ein **Manager** der im Hintergrund läuft und viele Aufgaben gleichzeitig überwacht:
#```
#   Event Loop schaut ständig:
#   ├── Request 1 fertig?  → nein, weiter warten
#   ├── Request 2 fertig?  → ja! → Ergebnis verarbeiten
#   ├── Request 3 fertig?  → nein, weiter warten
#   └── neue Aufgaben?     → ja! → starten

## "await" = "starte den Request, und während du wartest mach was anderes"


# Jeder Event Loop "besitzt" die Verbindungen die in ihm geöffnet wurden:
#```
# Test 1 → Loop A startet → DB-Verbindung in Loop A geöffnet
# Test 1 fertig → Loop A wird geschlossen → DB-Verbindung "gehört" zu totem Loop

# Test 2 → Loop B startet → versucht alte DB-Verbindung zu nutzen
# → CRASH: "Event loop is closed"


#  `NullPool` + `function scope` löst das:
# Test 1 → Loop A → eigene neue DB-Verbindung → Test fertig → alles geschlossen ✓
# Test 2 → Loop B → eigene neue DB-Verbindung → Test fertig → alles geschlossen ✓
