name: Build And Deploy Code

on: # wann sollte der Workflow ausgeführt werden
  push:
    branches: [main] # man kann mehrere branches angeben, z.B. [ main, develop ]
  pull_request: # für alle branches wäre --> on: [push, pull_request]
    branches: [main]

jobs: # die Jobs, die ausgeführt werden sollen
  job1:
    environment: Testing # Environment, in dem der Job ausgeführt wird, z.B. Testing, auf github festgelegt
    env: # env variablen, können nur in job 1 verwendet werden
      DB_PASSWORD: david
      DB_NAME: fastapi_test_db
      DB_PORT: ${{secrets.DB_PORT}}
      DB_HOSTNAME: ${{secrets.DB_HOSTNAME}} # auf github unter setting und dann secrets /variables, unter enivronment secrets (vorher neues env erstellen) die env variablen festlegen
      DB_USERNAME: postgres
      SECRETKEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: HS256
      EXPIRE_MIN: 30
    runs-on:
      ubuntu-latest # Betriebssystem, auf dem der Job ausgeführt wird


      # Service containers to run with `container-job`
    services:
      # Label used to access the service container ---> servcice name
      postgres:
        # Docker Hub image
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: david
          POSTGRES_DB: fastapi_test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps: # die Schritte, die in diesem Job ausgeführt werden sollen
      - name: Checkout code # Schritt 1: Code aus dem Repository auschecken
        uses: actions/checkout@v4 # Action, um den Code aus dem Repository zu holen, macht pull repo --> im marketplace ist es checkout@v4 genannt
      - name: Install python 3.11 # Schritt 2: Python 3.11 installieren
        uses: actions/setup-python@v5 # Action, um Python zu installieren, im marketplace ist es setup-python@v2 genannt
        with:
          python-version: 3.11 # die Version von Python, die installiert werden soll
      - name: Pip updaten # Schritt 3: Pip aktualisieren
        run: python -m pip install --upgrade pip # Befehl, um Pip zu aktualisieren (linux befehl)
      - name: Abhängigkeiten installieren # Schritt 4: Abhängigkeiten installieren
        run: pip install -r requirements.txt # Befehl, um die Abhängigkeiten
      - name: Tests ausführen # Schritt 5: Tests ausführen
        run: pytest
